package ru.nsu.gemuev.handlers;

public enum ClientHandlerState {
    AWAITING_AUTH_REQUEST,
    SENDING_AUTH_RESPONSE,
    AWAITING_CONNECTION_REQUEST,
    RESOLVING,
    SENDING_CONNECTION_RESPONSE,
    FORWARDING,
    CLOSED,
    SENDING_SOCKS_ERROR
}
